version: 2.0
orbs:
  maven: circleci/maven@0.0.10
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run

    steps:
      - checkout
      - run: echo "Hello World"
      - run: env
      - run: mvn clean test -Dtest=com.treasuredata.tdautomation.pluginautomation.TdExecutorTest#dev
